/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model004({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/model004.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_0002.geometry} material={materials['Material_0.002']} position={[-0.05, 0.4, -0.01]} rotation={[-0.03, 0, -0.02]} />
      <mesh geometry={nodes.Cube.geometry} material={materials['Material.001']} position={[0, -1.16, 0.08]} scale={[0.84, 0.16, 1]} />
    </group>
  )
}

useGLTF.preload('/model004.gltf')
