/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model003({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/model003.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_0.geometry} material={materials.Material_0} position={[-0.04, 1.15, 0.15]} />
    </group>
  )
}

useGLTF.preload('/model003.gltf')
