/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/model004.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_0002.geometry} material={materials['Material_0.002']} position={[-0.09, 1.39, 0.14]} rotation={[-0.03, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/model004.gltf')
