/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model002({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/model002.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Cube001.geometry} material={materials['default']} position={[53.7, 0, 50]} scale={[50, 0.1, 50]} />
      <mesh geometry={nodes.Cube.geometry} material={materials['default']} position={[-53.7, 0, 50]} scale={[50, 0.1, 50]} />
      <mesh geometry={nodes.Mesh_0.geometry} material={materials.Material_0} position={[-2.61, 0.37, 4.69]} rotation={[0, 0, -0.03]} />
      <mesh geometry={nodes.Mesh_0001.geometry} material={materials['Material_0.001']} position={[-2.72, 0.2, 10.65]} rotation={[0.02, 0.08, 0]} />
      <mesh geometry={nodes.Mesh_0002.geometry} material={materials['Material_0.002']} position={[-2.36, 0.2, 15.19]} rotation={[0.02, 0.04, 0]} />
      <mesh geometry={nodes.Mesh_0003.geometry} material={materials['Material_0.003']} position={[3.03, 0.2, 7.46]} rotation={[0.02, -0.02, 0]} />
      <mesh geometry={nodes.Mesh_0004.geometry} material={materials['Material_0.004']} position={[2.97, 0.2, 2.91]} rotation={[0.02, 0.01, 0]} />
      <mesh geometry={nodes.Mesh_0005.geometry} material={materials['Material_0.005']} position={[3.1, 0.2, 14.14]} rotation={[0.02, 0.02, 0]} />
      <mesh geometry={nodes.Cube002.geometry} material={materials['default']} position={[53.7, 0, -57.4]} scale={[50, 0.1, 50]} />
      <mesh geometry={nodes.Cube003.geometry} material={materials['default']} position={[-53.7, 0, -57.4]} scale={[50, 0.1, 50]} />
      <mesh geometry={nodes.Plane001.geometry} material={materials['Material.001']} position={[0, -0.1, 0]} scale={[3.7, 1, 100]} />
      <mesh geometry={nodes.Plane003.geometry} material={materials['Material.002']} position={[0, -0.1, -3.7]} rotation={[0, Math.PI / 2, 0]} scale={[3.7, 1, 100]} />
      <mesh geometry={nodes.Cube004.geometry} material={materials['Material.003']} position={[10.39, 4.26, 7.02]} scale={[4.51, 4.27, 5.29]} />
      <mesh geometry={nodes.Cube005.geometry} material={materials['Material.004']} position={[19.75, 8.33, 7.02]} scale={[4.51, 8.5, 5.29]} />
      <mesh geometry={nodes.Cube006.geometry} material={materials['Material.005']} position={[29.2, 12.8, 7.02]} scale={[4.51, 12.8, 5.29]} />
      <mesh geometry={nodes.Cube007.geometry} material={materials['Material.006']} position={[48.2, 4.24, 7.02]} scale={[4.51, 4.27, 5.29]} />
      <mesh geometry={nodes.Cube008.geometry} material={materials['Material.007']} position={[38.68, 8.5, 7.02]} scale={[4.51, 8.5, 5.29]} />
      <mesh geometry={nodes.door.geometry} material={materials['default']} position={[38.8, 1.78, 1.73]} rotation={[0, Math.PI / 2, 0]} scale={[0.11, 1.7, 0.9]} />
      <mesh geometry={nodes.door001.geometry} material={materials['default']} position={[36.4, 2.22, 1.73]} rotation={[0, Math.PI / 2, 0]} scale={[0.11, 0.94, 0.9]} />
      <mesh geometry={nodes.door002.geometry} material={materials['default']} position={[41.2, 2.22, 1.73]} rotation={[0, Math.PI / 2, 0]} scale={[0.11, 0.94, 0.9]} />
    </group>
  )
}

useGLTF.preload('/model002.gltf')
